version: '3.8'

services:
  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: educompare_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - educompare_network

  # FastAPI Backend
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: educompare_backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - educompare_network
    restart: unless-stopped

  # Celery Worker
  celery_worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: educompare_worker
    command: celery -A celery_app.worker worker --loglevel=info --concurrency=2
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - educompare_network
    restart: unless-stopped

  # Celery Flower (Monitor)
  celery_flower:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: educompare_flower
    command: celery -A celery_app.worker flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./.env:/app/.env
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - educompare_network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  educompare_network:
    driver: bridge 