// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfuapihpzucmfqqfmsnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmdWFwaWhwenVjbWZxcWZtc250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDAxMTEsImV4cCI6MjA2NjUxNjExMX0.KVJns82S5nv9-SSiEw6f4QhA0NfciwyARnfiCQZnwVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);